/*
 * AcmeWindow.java
 *
 * Created on February 19, 2008, 10:09 AM
 */

package acmegardening;

import java.sql.*; 
import javax.swing.JOptionPane;

/**
 *
 * @author  bdavis
 */
public class AcmeWindow extends javax.swing.JFrame {
    Connection conn; 
    /** Creates new form AcmeWindow */
    public AcmeWindow(Connection c) {
        initComponents();
        conn = c; 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        bCreate = new javax.swing.JButton();
        bDrop = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bReport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tLastName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tCity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tState = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tZip = new javax.swing.JTextField();
        bEnterOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acme Gardening Order Manager");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        bCreate.setText("Create");
        bCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateActionPerformed(evt);
            }
        });

        bDrop.setText("Drop");
        bDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDropActionPerformed(evt);
            }
        });

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bReport.setText("Report");
        bReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDrop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCreate)
                .addGap(18, 18, 18)
                .addComponent(bDrop)
                .addGap(18, 18, 18)
                .addComponent(bDelete)
                .addGap(18, 18, 18)
                .addComponent(bReport)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Database Manager", jPanel1);

        jLabel1.setText("Last Name:");

        jLabel2.setText("First Name:");

        jLabel3.setText("Address:");

        jLabel4.setText("City");

        jLabel5.setText("State");

        jLabel6.setText("Zip");

        bEnterOrder.setText("Enter Order");
        bEnterOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnterOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bEnterOrder))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(8, 8, 8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tState, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tZip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tCity, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(tAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))))
                .addGap(152, 152, 152))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(tState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEnterOrder)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateActionPerformed
        AcmeItem[] items = new AcmeItem[]{new AcmeItem("Rose Bush", 10),
            new AcmeItem("Lilac Bush", 20), new AcmeItem("Elm Tree", 30),
            new AcmeItem("Maple Tree", 40), new AcmeItem("Evergreen", 50)
        };

        try {
            AcmeDataAdapter.createCustomersTable(conn);
            AcmeDataAdapter.createOrdersTable(conn);
            AcmeDataAdapter.createItemsTable(conn);

            for (AcmeItem a : items) {
                AcmeDataAdapter.addItem(conn, a);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    "Connection Error ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bCreateActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    "Connection Error ", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_formWindowClosed

    private void bDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDropActionPerformed
        try {
            AcmeDataAdapter.dropCustomersTable(conn);
            AcmeDataAdapter.dropItemsTable(conn);
            AcmeDataAdapter.dropOrdersTable(conn);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    "Connection Error ", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bDropActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        try {
            AcmeDataAdapter.deleteCustomers(conn);
            AcmeDataAdapter.deleteOrders(conn);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    "Connection Error ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bEnterOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnterOrderActionPerformed
        boolean nameValidated = true; 
        if (this.tFirstName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter First Name",
                    "Customer Entry Error", JOptionPane.WARNING_MESSAGE);
            nameValidated = false; 
        } else if (this.tLastName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Last Name",
                    "Customer Entry Error", JOptionPane.WARNING_MESSAGE);
            nameValidated = false; 
        }
        
        if (!nameValidated) 
            return; 
        
        AcmeCustomer customer = null;
        try {
            customer = AcmeDataAdapter.findCustomer(conn, tLastName.getText(),
                    tFirstName.getText());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    "Connection Error ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //This customer is new
        if (customer == null) {
            boolean detailsValidated = true; 
            if (this.tAddress.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter Address",
                        "Customer Entry Error", JOptionPane.WARNING_MESSAGE);
                detailsValidated = false; 
            } else if (this.tCity.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter City",
                        "Customer Entry Error", JOptionPane.WARNING_MESSAGE);
                detailsValidated = false;
            } else if (this.tState.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter State",
                        "Customer Entry Error", JOptionPane.WARNING_MESSAGE);
                detailsValidated = false;
            } else if (this.tZip.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter Zip",
                        "Customer Entry Error", JOptionPane.WARNING_MESSAGE);
                detailsValidated = false;
            }

            if (detailsValidated) {
                try {
                    customer = new AcmeCustomer(tLastName.getText(), tFirstName.getText(),
                            tAddress.getText(), tCity.getText(),
                            tState.getText(), Integer.parseInt(tZip.getText()));
                    AcmeDataAdapter.addCustomer(conn, customer);
                    customer = AcmeDataAdapter.findCustomer(conn, 
                            customer.getLastName(), customer.getFirstName());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(),
                            "Connection Error ", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } else {
            //This is a repeat customer and we need to re-enter the customer 
            //details
            try {
                if (!this.tAddress.getText().equals("")) {
                    customer.setAddress(this.tAddress.getText());
                }
                if (!this.tCity.getText().equals("")) {
                    customer.setCity(this.tCity.getText());
                }
                if (!this.tState.getText().equals("")) {
                    customer.setState(tState.getText());
                }
                if (!this.tZip.getText().equals("")) {
                    customer.setZip(Integer.parseInt(tZip.getText()));
                }

                AcmeDataAdapter.updateCustomer(conn, customer);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(),
                        "Connection Error ", JOptionPane.ERROR_MESSAGE);
            }

        }
        
        if (customer != null) 
        {
            AcmeOrderWindow w = new AcmeOrderWindow(this, false, 
                    customer, conn); 
            w.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_bEnterOrderActionPerformed

    private void bReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReportActionPerformed
        AcmeReportWindow r = new AcmeReportWindow(this, true, conn);
        r.setVisible(true);
    }//GEN-LAST:event_bReportActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcmeWindow(null).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreate;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bDrop;
    private javax.swing.JButton bEnterOrder;
    private javax.swing.JButton bReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tAddress;
    private javax.swing.JTextField tCity;
    private javax.swing.JTextField tFirstName;
    private javax.swing.JTextField tLastName;
    private javax.swing.JTextField tState;
    private javax.swing.JTextField tZip;
    // End of variables declaration//GEN-END:variables
    
}
