/*
 * AcmeReportWindow.java
 *
 * Created on February 23, 2008, 8:25 AM
 */

package acmegardening;

import java.sql.*;
import javax.swing.JOptionPane; 
import java.util.ArrayList; 
import javax.swing.table.*; 
/**
 *
 * @author  davis
 */
public class AcmeReportWindow extends javax.swing.JDialog {
    
    /** Creates new form AcmeReportWindow */
    public AcmeReportWindow(java.awt.Frame parent, boolean modal, 
            Connection conn) {
        super(parent, modal);
        initComponents();
                
        try { 
        	java.sql.ResultSet report = AcmeDataAdapter.getReport(conn); 
            DefaultTableModel dtm = (DefaultTableModel)this.jTable1.getModel();
            while (report.next()) { 
            	dtm.addRow(new Object [] {
            			report.getInt("cust_id"), 
            			report.getString("lastname"), 
            			report.getString("firstname"), 
            			report.getString("address"), 
            			report.getString("city"), 
            			report.getString("state"), 
            			report.getInt("zip"), 
            			report.getInt("item_no"), 
            			report.getString("item_name"), 
            			report.getInt("price"), 
            			report.getInt("qty")
            	} ); 
            }
        } catch (Exception e) { 
        	JOptionPane.showMessageDialog(null, e.getMessage(),
                    "Connection Error ", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bOk = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Custid", "Last Name", "First Name", "Address", "City", "State", "Zip", "item_no", "item_name", "price", "quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(710, Short.MAX_VALUE)
                        .addComponent(bOk))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        dispose(); 
    }//GEN-LAST:event_bOkActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    AcmeReportWindow dialog = new AcmeReportWindow(new javax.swing.JFrame(), true,
                            AcmeDataAdapter.connect("wdavis", "wdavis"));
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception e) {
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
